name: Echo secrets and variables
on:
  push:
    branches:
      - main #Trigger this action when changes are pushed to the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_variable: "This is not a secret"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo environment variable
        run: echo "My environment variable is $my_variable"

      - name: Echo GH secret
        run: echo "MY GH secret is ${{secrets.MY_GITHUB_SECRET}}"
